/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sachit Rao
 */
import java.util.Scanner;
//3
//import cgpacalculator.pac1;


public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        coTF = new javax.swing.JTextField();
        maTF = new javax.swing.JTextField();
        dbmsTF = new javax.swing.JTextField();
        seTF = new javax.swing.JTextField();
        oopsTF = new javax.swing.JTextField();
        adaTF = new javax.swing.JTextField();
        kTF = new javax.swing.JTextField();
        conTF = new javax.swing.JTextField();
        dlabTF = new javax.swing.JTextField();
        alabTF = new javax.swing.JTextField();
        cletterTF = new javax.swing.JTextField();
        mletterTF = new javax.swing.JTextField();
        dletterTF = new javax.swing.JTextField();
        oletterTF = new javax.swing.JTextField();
        sletterTF = new javax.swing.JTextField();
        aletterTF = new javax.swing.JTextField();
        kletterTF = new javax.swing.JTextField();
        coletterTF = new javax.swing.JTextField();
        dlletterTF = new javax.swing.JTextField();
        alletterTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cgpaTF = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel1.setText("SGPA CALCULATOR");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Computer Organisation");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Mathematics-3");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Database Management");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("OOPS (java)");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Constitution");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Kannada");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("DBMS Lab");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Software Engineering");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("ADA Lab");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Alogotithm Design");

        maTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maTFActionPerformed(evt);
            }
        });

        kTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kTFActionPerformed(evt);
            }
        });

        cletterTF.setEditable(false);

        mletterTF.setEditable(false);

        dletterTF.setEditable(false);

        oletterTF.setEditable(false);

        sletterTF.setEditable(false);

        aletterTF.setEditable(false);

        kletterTF.setEditable(false);

        coletterTF.setEditable(false);

        dlletterTF.setEditable(false);

        alletterTF.setEditable(false);

        jScrollPane1.setViewportView(cgpaTF);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("SGPA");

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setText("GRADE");

        jLabel14.setText("MARKS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel14)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(maTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(coTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dbmsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oopsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(conTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dlabTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alabTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(coletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dlletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 78, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbmsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oopsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dlabTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dlletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(alletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alabTF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kTFActionPerformed

    private void maTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Calculate all the grades
        
        String coscore,mascore,dbmsscore,oopsscore,sescore,adascore,kscore,conscore,dlabscore,adalabscore;
        double cgpa=0;
        double total=0;
        
        coscore=coTF.getText();
        mascore=maTF.getText();
        dbmsscore=dbmsTF.getText();
        oopsscore=oopsTF.getText();
        sescore=seTF.getText();
       adascore=adaTF.getText();
        kscore=kTF.getText();
        conscore=conTF.getText();
        dlabscore=dlabTF.getText();
        adalabscore=alabTF.getText();
        
        double co=Double.parseDouble(coscore);
        double ma=Double.parseDouble(mascore);
        double db=Double.parseDouble(dbmsscore);
        double oops=Double.parseDouble(oopsscore);
        double se=Double.parseDouble(sescore);
        double ada=Double.parseDouble(adascore);
        double k=Double.parseDouble(kscore);
        double dlab=Double.parseDouble(dlabscore);
        double adalab=Double.parseDouble(adalabscore);
        double con=Double.parseDouble(conscore);
        
        
        
        
        
        
        try
        {
            if(co>100)
            {
                throw new Exception("error");
            }
            
            
                
        }
        
        catch(Exception e)
        {
            cletterTF.setText("X "+e);
        }
        
        
        
        
        //co
        
        if(co>=90 && co<=100)
        {
            
            cletterTF.setText("S");
            total=((10*4)+total);
        }
        else if(co>=80 && co<90) 
        {
            cletterTF.setText("A");
            total=((9*4)+total);
        }
        
        else if(co>=70 && co<80) 
        {
            cletterTF.setText("B");
            total=((8*4)+total);
        }
        
        else if(co>=60 && co<70) 
        {
            cletterTF.setText("C");
            total=((7*4)+total);
        }
        else if(co>=50 && co<60) 
        {
            cletterTF.setText("D");
            total=((6*4)+total);
        }
        
         else if(co>=40 && co<50) 
        {
            cletterTF.setText("E");
            total=((5*4)+total);
        }
        
          else if(co<40)
        {
            cletterTF.setText("F");
            total=((0*4)+total);
        } 
        
        //oops
        if(oops>=90)
        {
            
            oletterTF.setText("S");
            total=((10*4)+total);
        }
        else if(oops>=80 && oops<90) 
        {
            oletterTF.setText("A");
            total=((9*4)+total);
        }
        
        else if(oops>=70 && oops<80) 
        {
            oletterTF.setText("B");
            total=((8*4)+total);
        }
        
        else if(oops>=60 && oops<70) 
        {
            oletterTF.setText("C");
            total=((7*4)+total);
        }
        else if(oops>=50 && oops<60) 
        {
            oletterTF.setText("D");
            total=((6*4)+total);
        }
        
         else if(oops>=40 && oops<50) 
        {
            oletterTF.setText("E");
            total=((5*4)+total);
        }
        
          else if(oops<40)
        {
            oletterTF.setText("F");
            total=((0*4)+total);
        } 
        
        
        //se
        if(se>=90)
        {
            
            sletterTF.setText("S");
            total=((10*3)+total);
        }
        else if(se>=80 && se<90) 
        {
            sletterTF.setText("A");
            total=((9*3)+total);
        }
        
        else if(se>=70 && se<80) 
        {
            sletterTF.setText("B");
            total=((8*3)+total);
        }
        
        else if(se>=60 && se<70) 
        {
            sletterTF.setText("C");
            total=((7*3)+total);
        }
        else if(se>=50 && se<60) 
        {
            sletterTF.setText("D");
            total=((6*3)+total);
        }
        
         else if(se>=40 && se<50) 
        {
            sletterTF.setText("E");
            total=((5*3)+total);
        }
        
          else if(se<40)
        {
            sletterTF.setText("F");
            total=((0*3)+total);
        } 
        
        
        
       //maths
       
        if(ma>=90)
        {
            mletterTF.setText("S");
            total=((10*3)+total);
        }
        else if(ma>=80 && ma<90) 
        {
            mletterTF.setText("A");
            total=((9*3)+total);
        }
        
        else if(ma>=70 && ma<80) 
        {
            mletterTF.setText("B");
           total=((8*3)+total);
        }
        
        else if(ma>=60 && ma<70) 
        {
            mletterTF.setText("C");
          total=((7*3)+total);
        }
        else if(ma>=50 && ma<60) 
        {
            mletterTF.setText("D");
            total=((6*3)+total);
        }
        
         else if(ma>=40 && ma<50) 
        {
            mletterTF.setText("E");
        total=((5*3)+total);
        }
        
          else if(ma<40)
        {
            mletterTF.setText("F");
          total=((10*3)+total);
        }  
        //dbms
           
        
        if(db>=90)
        {
            dletterTF.setText("S");
            total=((10*3)+total);
        }
        
        
        
       
        
       
        try
        {
        if(db>=80 && db<90)
        {
            dletterTF.setText("A");
           total=((9*3)+total);
        }
        }
        
        catch(Exception e)
        {
            
            dletterTF.setText("error");
            
        }
        
        if(db>=70 && db<80)
        {
            dletterTF.setText("B");
            total=((8*3)+total);;
        }
        
        else if(db>=60 && db<70)
        {
            dletterTF.setText("C");
            total=((7*3)+total);
        }
        else if(db>=50 && db<60)
        {
            dletterTF.setText("D");
            total=((6*3)+total);
        }
        
         else if(db>=40 && db<50)
        {
            dletterTF.setText("E");
          total=((5*3)+total);
        }
        
          else if(db<40)
        {
            dletterTF.setText("F");
            total=((0*3)+total);
        } 
        
        //ada
        
        if(ada>=90)
        {
            aletterTF.setText("S");
            total=((10*3)+total);
        }
        else if(ada>=80 && ada<90)
        {
            aletterTF.setText("A");
           total=((9*3)+total);
        }
        
        else if(ada>=70 && ada<80)
        {
            aletterTF.setText("B");
            total=((8*3)+total);;
        }
        
        else if(ada>=60 && ada<70)
        {
            aletterTF.setText("C");
            total=((7*3)+total);
        }
        else if(ada>=50 && ada<60)
        {
            aletterTF.setText("D");
            total=((6*3)+total);
        }
        
         else if(ada>=40 && ada<50)
        {
            aletterTF.setText("E");
          total=((5*3)+total);
        }
        
          else if(ada<40)
        {
            aletterTF.setText("F");
            total=((0*3)+total);
        } 
        
        //constitution
        
        
        if(con>=90)
        {
            coletterTF.setText("S");
            total=((10*1)+total);
        }
        else if(con>=80 && con<90)
        {
            coletterTF.setText("A");
           total=((9*1)+total);
        }
        
        else if(con>=70 && con<80)
        {
            coletterTF.setText("B");
            total=((8*1)+total);;
        }
        
        else if(con>=60 && con<70)
        {
            coletterTF.setText("C");
            total=((7*1)+total);
        }
        else if(con>=50 && con<60)
        {
            coletterTF.setText("D");
            total=((6*1)+total);
        }
        
         else if(con>=40 && con<50)
        {
            coletterTF.setText("E");
          total=((5*1)+total);
        }
        
          else if(con<40)
        {
            coletterTF.setText("F");
            total=((0*1)+total);
        } 
        
        //kannada
        if(k>=90)
        {
            kletterTF.setText("S");
            total=((10*1)+total);
        }
        else if(k>=80 && k<90)
        {
            kletterTF.setText("A");
           total=((9*1)+total);
        }
        
        else if(k>=70 && k<80)
        {
            kletterTF.setText("B");
            total=((8*1)+total);;
        }
        
        else if(k>=60 && k<70)
        {
            kletterTF.setText("C");
            total=((7*1)+total);
        }
        else if(k>=50 && k<60)
        {
            kletterTF.setText("D");
            total=((6*1)+total);
        }
        
         else if(k>=40 && k<50)
        {
            kletterTF.setText("E");
          total=((5*1)+total);
        }
        
          else if(k<40)
        {
            kletterTF.setText("F");
            total=((0*1)+total);
        } 
        
        //dlab
        
        if(dlab>=90)
        {
            dlletterTF.setText("S");
            total=((10*1.5)+total);
        }
        else if(dlab>=80 && dlab<90)
        {
            dlletterTF.setText("A");
           total=((9*1.5)+total);
        }
        
        else if(dlab>=70 && dlab<80)
        {
            dlletterTF.setText("B");
            total=((8*1.5)+total);;
        }
        
        else if(dlab>=60 && dlab<70)
        {
            dlletterTF.setText("C");
            total=((7*1.5)+total);
        }
        else if(dlab>=50 && dlab<60)
        {
            dlletterTF.setText("D");
            total=((6*1.5)+total);
        }
        
         else if(dlab>=40 && dlab<50)
        {
            dlletterTF.setText("E");
          total=((5*1.5)+total);
        }
        
          else if(dlab<40)
        {
            dlletterTF.setText("F");
            total=((0*1.5)+total);
        } 
       
        //ada lab
        
         if(adalab>=90)
        {
            alletterTF.setText("S");
            total=((10*1.5)+total);
        }
        else if(adalab>=80 && adalab<90)
        {
            alletterTF.setText("A");
           total=((9*1.5)+total);
        }
        
        else if(adalab>=70 && adalab<80)
        {
            alletterTF.setText("B");
            total=((8*1.5)+total);;
        }
        
        else if(adalab>=60 && adalab<70)
        {
            alletterTF.setText("C");
            total=((7*1.5)+total);
        }
        else if(adalab>=50 && adalab<60)
        {
            alletterTF.setText("D");
            total=((6*1.5)+total);
        }
        
         else if(adalab>=40 && adalab<50)
        {
            alletterTF.setText("E");
          total=((5*1.5)+total);
        }
        
          else if(adalab<40)
        {
            alletterTF.setText("F");
            total=((0*1.5)+total);
        } 
        
        cgpa=total/24;
        cgpaTF.setText(Double.toString(cgpa));
        
        
 
    
 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        
       
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            
            public void run() 
            {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adaTF;
    private javax.swing.JTextField alabTF;
    private javax.swing.JTextField aletterTF;
    private javax.swing.JTextField alletterTF;
    private javax.swing.JTextPane cgpaTF;
    private javax.swing.JTextField cletterTF;
    private javax.swing.JTextField coTF;
    private javax.swing.JTextField coletterTF;
    private javax.swing.JTextField conTF;
    private javax.swing.JTextField dbmsTF;
    private javax.swing.JTextField dlabTF;
    private javax.swing.JTextField dletterTF;
    private javax.swing.JTextField dlletterTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kTF;
    private javax.swing.JTextField kletterTF;
    private javax.swing.JTextField maTF;
    private javax.swing.JTextField mletterTF;
    private javax.swing.JTextField oletterTF;
    private javax.swing.JTextField oopsTF;
    private javax.swing.JTextField seTF;
    private javax.swing.JTextField sletterTF;
    // End of variables declaration//GEN-END:variables
}
